{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-tooling-preview",
    "version": "1.2.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-1.2.0-alpha05.aar",
          "url": "ui-tooling-preview-1.2.0-alpha05.aar",
          "size": 12058,
          "sha512": "235ce50528ca30edb1f7b518380ba68838e77573ee0fbf314600671b74d27786ed72a895e45fc7fe675ba1b48fad103738af854ab253ba83026245717063698d",
          "sha256": "de872573281faf4c17373cbb504fe4899955f18488858e645c464759b744c99f",
          "sha1": "5eb2edd467e639afab2507cdddec7aa09eb1279e",
          "md5": "9ab48ec0674e2e8cd7f7e24c17a44620"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-1.2.0-alpha05.aar",
          "url": "ui-tooling-preview-1.2.0-alpha05.aar",
          "size": 12058,
          "sha512": "235ce50528ca30edb1f7b518380ba68838e77573ee0fbf314600671b74d27786ed72a895e45fc7fe675ba1b48fad103738af854ab253ba83026245717063698d",
          "sha256": "de872573281faf4c17373cbb504fe4899955f18488858e645c464759b744c99f",
          "sha1": "5eb2edd467e639afab2507cdddec7aa09eb1279e",
          "md5": "9ab48ec0674e2e8cd7f7e24c17a44620"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooling-preview-1.2.0-alpha05-sources.jar",
          "url": "ui-tooling-preview-1.2.0-alpha05-sources.jar",
          "size": 7973,
          "sha512": "38f831d85a0115d4143bb9882a35c2e5603a3fbd3cee4dce1cba269b47385de12fdc5a51a9d734c874dfb5ddf4fc461f1fd245d7a80d0f4fc8c253bd1e3948c1",
          "sha256": "0f91bdedffc810244331bee9dc46194902737d347169e6cf1c5968dc1db0b1c2",
          "sha1": "1b97ee7da67d0051dae7cbff03e7e8228dd0d9e8",
          "md5": "a6374b73f8095b1392ff74ad83d40f8f"
        }
      ]
    }
  ]
}
